
obj-$(CONFIG_NOTHING_WRITRBACK_KMSG)    += nothing_writeback_kmsg.o
obj-$(CONFIG_NOTHING_DISK_USAGE)        += nothing_disk_usage.o
obj-$(CONFIG_NOTHING_DISK_USAGE)        += nothing_readahead_trace.o
obj-$(CONFIG_NOTHING_TASK_MEMINFO)      += nothing_task_meminfo.o
obj-$(CONFIG_NOTHING_TASK_INFO)         += nothing_task_info.o
