# SPDX-License-Identifier: GPL-2.0
# makefile for tfa98xx driver

ccflags-y += -DCONFIG_MTK_PLATFORM

snd-soc-tfa98xx-objs += tfa98xx.o tfa_container.o tfa_dsp.o tfa_init.o
obj-$(CONFIG_SND_SOC_TFA9874) += snd-soc-tfa98xx.o
